"""
WFA Spelling Shed Rules Database
All 216 rules across Stages 1-6.
Each entry: (stage, step, title, words_list, rule_type)
  rule_type: 0=standard, 1=challenge, 2=revision

Challenge Words steps are excluded from the weekly planner current-rule dropdown.
Revision Words steps can be used as revision rules.
"""

SPELLING_RULES = [
    # ── Stage 1 ────────────────────────────────────────────────────────────
    (1,1,"Words ending 'ff','ll','ss','zz','ck'",["puff","bell","grass","buzz","clock"],0),
    (1,2,"/k/ sound as 'k' and 'nk'",["bank","pink","think","kit","mask"],0),
    (1,3,"'tch' trigraph",["catch","fetch","kitchen","switch","hutch"],0),
    (1,4,"Plurals '-s' and '-es'",["flowers","boxes","brushes","lunches","churches"],0),
    (1,5,"Adding '-ing' and '-ed'",["looking","buzzing","jumped","helping","fizzed"],0),
    (1,6,"Prefix 'un-' and suffixes '-er','-est'",["fresher","unhappy","hardest","unfair","unlock"],0),
    (1,7,"Compound words and unstressed vowels",["pocket","balloon","football","bedroom","starfish"],0),
    (1,8,"Digraphs 'ai' and 'oi'",["rain","point","wait","coin","afraid"],0),
    (1,9,"Digraphs 'ay' and 'oy'",["day","play","enjoy","toy","clay"],0),
    (1,10,"Split digraph 'a_e'",["made","take","came","safe","awake"],0),
    (1,11,"Split digraph 'e_e'",["even","complete","these","athlete","theme"],0),
    (1,12,"Split digraph 'i_e'",["five","ride","like","time","slide"],0),
    (1,13,"Split digraph 'o_e'",["home","hope","spoke","joke","bone"],0),
    (1,14,"Split digraph 'u_e'",["June","rude","huge","tune","flute"],0),
    (1,15,"Digraph 'ar'",["car","park","arm","garden","shark"],0),
    (1,16,"Digraph 'ee'",["feel","tree","green","meet","feet"],0),
    (1,17,"'ea' making /ee/",["each","peach","teach","leaf","beak"],0),
    (1,18,"'ea' making /e/",["head","bread","meant","instead","dead"],0),
    (1,19,"Stressed 'er'",["verb","her","term","person","germ"],0),
    (1,20,"Unstressed 'er'",["better","summer","sister","after","winter"],0),
    (1,21,"Digraphs 'ir' and 'ur'",["girl","shirt","turn","hurt","burst"],0),
    (1,22,"'oo' making /oo/",["food","moon","zoo","soon","spoon"],0),
    (1,23,"'oo' making /u/",["book","cook","foot","good","shook"],0),
    (1,24,"'oa' and 'oe' making /oa/",["goat","boat","toe","road","coat"],0),
    (1,25,"'ou' making /ow/",["out","mouth","sound","proud","found"],0),
    (1,26,"'ow' making /ow/ or /oa/",["down","town","own","grow","snow"],0),
    (1,27,"Words ending 'y' /ee/ and 've' /v/",["very","happy","give","have","love"],0),
    (1,28,"Digraphs 'ue' and 'ew'",["blue","clue","true","threw","new"],0),
    (1,29,"'ie' making /igh/",["lie","tie","pie","cried","fried"],0),
    (1,30,"'ie' making /ee/",["chief","thief","piece","field","belief"],0),
    (1,31,"Trigraph 'igh'",["night","light","bright","right","fright"],0),
    (1,32,"Digraph 'or' and trigraph 'ore'",["morning","north","more","score","shore"],0),
    (1,33,"'aw' and 'au' making /or/",["saw","draw","crawl","author","August"],0),
    (1,34,"Trigraphs 'air' and 'ear'",["chair","pair","ear","hear","year"],0),
    (1,35,"'ear' and 'are' making /air/",["bear","wear","bare","care","dare"],0),
    (1,36,"Digraphs 'ph' and 'wh'",["dolphin","elephant","wheel","when","which"],0),
    # ── Stage 2 ────────────────────────────────────────────────────────────
    (2,1,"'dge' making /j/",["badge","bridge","fudge","judge","wedge"],0),
    (2,2,"'ge' making /j/",["change","range","strange","sponge","fringe"],0),
    (2,3,"'g' making /j/",["gem","giant","giraffe","magic","engine"],0),
    (2,4,"'c' making /s/ before e, i, y",["ice","city","fancy","circle","circus"],0),
    (2,5,"'kn' and 'gn' making /n/",["knock","know","knee","knight","gnome"],0),
    (2,6,"Challenge Words",["door","find","kind","child","because"],1),
    (2,7,"'wr' making /r/",["write","wrap","wrong","wren","wrote"],0),
    (2,8,"Words ending 'le'",["table","apple","bottle","little","eagle"],0),
    (2,9,"Words ending 'el'",["camel","tunnel","jewel","travel","towel"],0),
    (2,10,"Words ending 'al'",["metal","capital","animal","equal","local"],0),
    (2,11,"Words ending 'il'",["pencil","fossil","pupil","evil","basil"],0),
    (2,12,"Challenge Words",["wild","climb","most","both","cold"],1),
    (2,13,"'y' making /igh/",["cry","fly","dry","try","shy"],0),
    (2,14,"Adding '-es' to words ending 'y'",["tries","flies","babies","carries","lorries"],0),
    (2,15,"Adding '-ed' to words ending 'y'",["copied","replied","spied","applied","supplied"],0),
    (2,16,"Adding '-er' and '-est' to words ending 'y'",["happier","happiest","tidier","tidiest","funnier"],0),
    (2,17,"Adding '-ing' to words ending 'e'",["hiking","smiling","writing","hoping","caring"],0),
    (2,18,"Challenge Words",["every","great","break","beautiful","pretty"],1),
    (2,19,"Adding '-er','-est','-ed' to words ending 'e'",["nicer","safer","hoped","loved","largest"],0),
    (2,20,"Adding '-ing' to single syllable words",["patting","running","hopping","sitting","dropping"],0),
    (2,21,"Adding '-ed' to single syllable words",["patted","hummed","dropped","clapped","dragged"],0),
    (2,22,"'a' making /or/",["all","ball","walk","call","always"],0),
    (2,23,"'o' making /u/",["other","mother","some","money","done"],0),
    (2,24,"Challenge Words",["last","father","class","path","bath"],1),
    (2,25,"'ey' making /ee/",["key","donkey","monkey","valley","journey"],0),
    (2,26,"'a' making /o/",["want","watch","wander","quality","squash"],0),
    (2,27,"'or' and 'ar' making /er/ or /or/",["word","work","world","warm","war"],0),
    (2,28,"'si' and 's' making /zh/",["television","measure","pleasure","vision","leisure"],0),
    (2,29,"Suffixes '-ment' and '-ness'",["enjoyment","agreement","darkness","sadness","kindness"],0),
    (2,30,"Suffixes '-ful', '-less' and '-ly'",["careful","thankful","boldly","happily","hopeless"],0),
    (2,31,"Homophones",["there","their","here","hear","sea"],0),
    (2,32,"Homophones and near homophones",["quiet","quite","bare","bear","sun"],0),
    (2,33,"Words ending '-tion'",["station","fiction","motion","action","fraction"],0),
    (2,34,"Apostrophe for contraction",["can't","didn't","hasn't","couldn't","wasn't"],0),
    (2,35,"Apostrophe for possession",["Megan's","Sam's","child's","boy's","dog's"],0),
    (2,36,"Challenge Words",["whole","any","many","clothes","people"],1),
    # ── Stage 3 ────────────────────────────────────────────────────────────
    (3,1,"'ou' making /ow/",["mouth","sprout","sound","hound","proud"],0),
    (3,2,"'ou' making /u/",["touch","double","country","trouble","young"],0),
    (3,3,"'y' making /i/",["symbol","gym","myth","pyramid","mystery"],0),
    (3,4,"Words ending '-sure'",["treasure","measure","leisure","pleasure","pressure"],0),
    (3,5,"Words ending '-ture'",["adventure","future","picture","nature","creature"],0),
    (3,6,"Challenge Words",["actual","bicycle","island","often","popular"],1),
    (3,7,"Prefix 're-'",["redo","return","refresh","replay","reappear"],0),
    (3,8,"Prefix 'dis-'",["disappoint","disobey","disappear","disable","disagree"],0),
    (3,9,"Prefix 'mis-'",["mistake","mislead","misbehave","misplace","misread"],0),
    (3,10,"'-ing','-er','-ed' on multisyllabic (stressed)",["forgetting","forgotten","beginning","propelled","preferred"],0),
    (3,11,"'-ing','-en','-ed' on multisyllabic (unstressed)",["developing","developed","limiting","covering","listened"],0),
    (3,12,"Challenge Words",["centre","disappear","heart","minute","notice"],1),
    (3,13,"Digraph 'ai' and tetragraph 'aigh'",["straight","strainer","waist","snail","painter"],0),
    (3,14,"Digraph 'ei' and tetragraph 'eigh'",["freight","vein","weigh","eight","reign"],0),
    (3,15,"'ey' making /ai/",["obey","prey","they","convey","grey"],0),
    (3,16,"Suffix '-ly'",["calmly","exactly","bravely","boldly","quickly"],0),
    (3,17,"Homophones",["great","grate","meet","meat","main"],0),
    (3,18,"Challenge Words",["build","beautiful","great","break","steak"],1),
    (3,19,"Words ending '-al'",["arrival","comical","magical","national","tropical"],0),
    (3,20,"Words ending '-le'",["battle","humble","terrible","possible","capable"],0),
    (3,21,"'-ly' where base ends 'le'",["gently","simply","humbly","nobly","terribly"],0),
    (3,22,"'-ly' where base ends '-ic'",["basically","frantically","logically","tragically","magically"],0),
    (3,23,"'-ly' exceptions",["truly","slyly","fully","duly","shyly"],0),
    (3,24,"Challenge Words",["address","mention","occasionally","certainly","probably"],1),
    (3,25,"Suffix '-er' (person who)",["teacher","stretcher","catcher","butcher","watcher"],0),
    (3,26,"'ch' making /k/",["scheme","chorus","echo","character","school"],0),
    (3,27,"Words ending '-gue' and '-que'",["vague","league","plague","antique","unique"],0),
    (3,28,"'sc' making /s/",["science","scene","scissors","fascinate","descend"],0),
    (3,29,"Homophones",["ball","bawl","break","brake","fair"],0),
    (3,30,"Challenge Words",["accidentally","breathe","century","consider","guard"],1),
    (3,31,"Words ending '-sion' /zhun/",["vision","confusion","division","invasion","decision"],0),
    (3,32,"Challenge Words",["special","strange","difficult","important","length"],1),
    (3,33,"Revision Words",["exactly","bravely","pleasure","island","decide"],2),
    (3,34,"Revision Words",["freight","hourly","scented","descend","plaque"],2),
    (3,35,"Revision Words",["teacher","scheme","mention","crescent","eighteen"],2),
    (3,36,"Revision Words",["disappear","reaction","committed","capable","confusion"],2),
    # ── Stage 4 ────────────────────────────────────────────────────────────
    (4,1,"Homophones",["accept","except","peace","piece","plain"],0),
    (4,2,"Prefix 'in-' (not)",["inability","inactive","incorrect","invisible","insecure"],0),
    (4,3,"Prefixes 'il-','im-','ir-'",["illegal","immature","impossible","irregular","irresponsible"],0),
    (4,4,"Prefix 'sub-'",["subdivide","submarine","submerge","subtitle","subway"],0),
    (4,5,"Prefix 'inter-'",["interact","intercity","intercom","interfere","international"],0),
    (4,6,"Challenge Words",["strength","grammar","calendar","women","believe"],1),
    (4,7,"Words ending '-ation' (from -ate verbs)",["information","sensation","preparation","vibration","decoration"],0),
    (4,8,"Words ending '-ation' (other verbs)",["adoration","admiration","coronation","observation","generation"],0),
    (4,9,"Words ending '-ly'",["sadly","completely","wildly","bravely","gently"],0),
    (4,10,"Words ending '-lly'",["usually","finally","beautifully","thoughtfully","carefully"],0),
    (4,11,"'ch' making /sh/ (French origin)",["chef","chalet","machine","brochure","chandelier"],0),
    (4,12,"Challenge Words",["favourite","complete","continue","experiment","February"],1),
    (4,13,"Words ending '-sion' /zhun/",["expansion","extension","comprehension","tension","suspension"],0),
    (4,14,"Words ending '-ous'",["poisonous","dangerous","mountainous","marvellous","enormous"],0),
    (4,15,"Words ending '-ous' (ge retained)",["courageous","outrageous","nervous","famous","adventurous"],0),
    (4,16,"Suffix added to words ending 'y'",["merriment","happiness","plentiful","penniless","prettiest"],0),
    (4,17,"Words ending '-ious' and '-eous'",["serious","obvious","curious","hideous","spontaneous"],0),
    (4,18,"Challenge Words",["extreme","although","breath","caught","different"],1),
    (4,19,"'au' making /or/",["automatic","August","launch","haul","astronaut"],0),
    (4,20,"Words ending '-tion'",["invention","injection","action","hesitation","completion"],0),
    (4,21,"Words ending '-sion' /shun/",["expression","discussion","confession","permission","impression"],0),
    (4,22,"Words ending '-cian'",["musician","magician","electrician","politician","mathematician"],0),
    (4,23,"Adverbs of manner",["reluctantly","quickly","generously","curiously","furiously"],0),
    (4,24,"Challenge Words",["surprise","separate","height","potatoes","through"],1),
    (4,25,"Homophones",["scene","seen","affect","effect","hear"],0),
    (4,26,"'c' before i and e (soft c)",["circle","century","circus","princess","celebrate"],0),
    (4,27,"Word roots 'sol' and 'real'",["solve","insoluble","real","reality","solution"],0),
    (4,28,"Word roots 'phon' and 'sign'",["signal","telephone","microphone","homophone","phonics"],0),
    (4,29,"Prefixes 'super-','anti-','auto-'",["supermarket","superhero","antiseptic","anticlockwise","autograph"],0),
    (4,30,"Prefix 'bi-' (two)",["bicycle","biplane","biped","biannual","bilingual"],0),
    (4,31,"Challenge Words",["guide","possess","accident","occasion","Wednesday"],1),
    (4,32,"Plural possessive apostrophes",["girls'","boys'","babies'","children's","men's"],0),
    (4,33,"Revision Words",["expression","musician","reluctantly","scene","circle"],2),
    (4,34,"Revision Words",["incorrect","illegible","international","believe","wildly"],2),
    (4,35,"Revision Words",["gently","separate","affect","unexpectedly","potatoes"],2),
    (4,36,"Revision Words",["disappear","specifically","reaction","committed","capable"],2),
    # ── Stage 5 ────────────────────────────────────────────────────────────
    (5,1,"Words ending '-tious' and '-ious'",["ambitious","amphibious","fictitious","infectious","notorious"],0),
    (5,2,"Words ending '-cious'",["atrocious","delicious","ferocious","gracious","suspicious"],0),
    (5,3,"Words ending '-cial'",["artificial","beneficial","crucial","facial","official"],0),
    (5,4,"Words ending '-tial'",["circumstantial","confidential","essential","influential","potential"],0),
    (5,5,"Words ending '-cial' and '-tial'",["commercial","financial","initial","palatial","spatial"],0),
    (5,6,"Challenge Words",["appreciate","cemetery","environment","sufficient","vegetable"],1),
    (5,7,"Words ending '-ant'",["abundant","brilliant","constant","elegant","tolerant"],0),
    (5,8,"Words ending '-ance' and '-ancy'",["abundance","brilliance","elegance","extravagance","tolerance"],0),
    (5,9,"Words ending '-ent' and '-ence'",["competence","confidence","eloquence","intelligence","frequent"],0),
    (5,10,"Words ending '-able' and '-ible'",["comfortable","dependable","enjoyable","horrible","possible"],0),
    (5,11,"Words ending '-ably' and '-ibly'",["comfortably","dependably","horribly","incredibly","terribly"],0),
    (5,12,"Challenge Words",["accommodate","available","controversy","marvellous","sincerely"],1),
    (5,13,"'-able' where root 'e' remains",["agreeable","changeable","knowledgeable","noticeable","replaceable"],0),
    (5,14,"Adverbs of time",["afterwards","eventually","immediately","previously","recently"],0),
    (5,15,"Suffixes where base ends 'fer'",["conferring","difference","preference","preferred","referring"],0),
    (5,16,"Silent first letters",["knife","knight","knuckle","wreath","wreckage"],0),
    (5,17,"Silent letters",["ascend","doubt","island","solemn","thistle"],0),
    (5,18,"Challenge Words",["ancient","amateur","awkward","criticise","equipment"],1),
    (5,19,"'ie' after 'c'",["society","deficient","efficient","science","species"],0),
    (5,20,"'ei' making /ee/",["caffeine","conceive","deceive","perceive","receive"],0),
    (5,21,"'ough' making /or/",["afterthought","bought","brought","fought","thought"],0),
    (5,22,"Words containing 'ough'",["although","bough","dough","enough","plough"],0),
    (5,23,"Adverbs of possibility and frequency",["certainly","definitely","frequently","occasionally","probably"],0),
    (5,24,"Challenge Words",["communicate","conscience","nuisance","queue","restaurant"],1),
    (5,25,"Homophones / near homophones",["advice","advise","licence","license","practice"],0),
    (5,26,"Homophones",["aisle","isle","allowed","aloud","altar"],0),
    (5,27,"Homophones",["bridal","bridle","heard","herd","morning"],0),
    (5,28,"Homophones / near homophones",["affect","effect","dessert","desert","who's"],0),
    (5,29,"Homophones / near homophones",["cereal","serial","complement","compliment","stationary"],0),
    (5,30,"Challenge Words",["achieve","apparent","bargain","bruise","community"],1),
    (5,31,"Words with hyphens",["co-author","co-operate","re-educate","re-enter","re-evaluate"],0),
    (5,32,"Challenge Words",["afterwards","amateur","ancient","changeable","knight"],1),
    (5,33,"Revision Words",["accompany","achieve","advice","affect","aisle"],2),
    (5,34,"Revision Words",["ascend","awkward","conscience","dough","probably"],2),
    (5,35,"Revision Words",["ball","bawl","break","brake","fair"],2),
    (5,36,"Revision Words",["aloud","community","complement","desert","device"],2),
    # ── Stage 6 ────────────────────────────────────────────────────────────
    (6,1,"Short /i/ spelled 'y'",["antonym","crystal","lyrics","mystery","symbol"],0),
    (6,2,"Long /igh/ spelled 'y'",["apply","hygiene","hyphen","identify","multiply"],0),
    (6,3,"Challenge Words",["ancient","cemetery","criticise","equipped","government"],1),
    (6,4,"'cial' /shul/ after vowel",["antisocial","artificial","facial","official","special"],0),
    (6,5,"'tial' /shul/",["confidential","essential","influential","martial","potential"],0),
    (6,6,"Challenge Words",["amateur","category","correspond","environment","frequently"],1),
    (6,7,"Challenge Words",["appreciate","communicate","exaggerate","harass","marvellous"],1),
    (6,8,"/oa/ spelled 'ou' or 'ow'",["blown","mould","shoulder","soul","window"],0),
    (6,9,"Soft c spelled 'ce'",["celebrate","cemetery","certificate","deceased","December"],0),
    (6,10,"Challenge Words",["apparent","committee","guarantee","parliament","recommend"],1),
    (6,11,"/f/ spelled 'ph'",["alphabet","dolphin","elephant","graph","phone"],0),
    (6,12,"Challenge Words",["according","awkward","conscious","dictionary","familiar"],1),
    (6,13,"Suffix '-ably'",["adorably","believably","comfortably","noticeably","reasonably"],0),
    (6,14,"Suffix '-ible'",["forcible","horrible","incredible","possible","responsible"],0),
    (6,15,"Challenge Words",["attached","desperate","excellent","hindrance","mischievous"],1),
    (6,16,"Suffix '-ibly'",["forcibly","horribly","incredibly","possibly","responsibly"],0),
    (6,17,"Words ending '-ent' and '-ence'",["convenience","convenient","difference","different","excellence"],0),
    (6,18,"Challenge Words",["accommodate","available","competition","determined","existence"],1),
    (6,19,"Challenge Words",["aggressive","bruise","embarrass","interrupt","pronunciation"],1),
    (6,20,"Words ending '-er','-or','-ar'",["calendar","computer","customer","radiator","shoulder"],0),
    (6,21,"Challenge Words",["achieve","bargain","controversy","disastrous","foreign"],1),
    (6,22,"Words beginning 'acc-'",["accentuate","access","accommodate","accompany","accomplish"],0),
    (6,23,"Prefixes 'dis-','un-','over-','im-'",["disappointed","dissatisfied","impatient","overreact","unnecessary"],0),
    (6,24,"Challenge Words",["accompany","average","conscience","immediately","necessary"],1),
    (6,25,"Words from other languages",["ballet","blizzard","bungalow","gymkhana","pyjamas"],0),
    (6,26,"Grammar Vocabulary 1",["adverb","bracket","clause","cohesion","determiner"],0),
    (6,27,"Grammar Vocabulary 2",["active","antonym","colon","ellipsis","hyphen"],0),
    (6,28,"Prefix 'over-'",["overbalance","overcoat","overlooked","overreact","overturned"],0),
    (6,29,"Suffix '-ful'",["beautiful","doubtful","faithful","fearful","merciful"],0),
    (6,30,"Adjectives: settings",["bustling","majestic","picturesque","sinister","tranquil"],0),
    (6,31,"Adjectives: feelings",["apprehensive","despondent","euphoric","incensed","jittery"],0),
    (6,32,"Adjectives: characters",["amiable","courageous","disagreeable","gargantuan","valiant"],0),
    (6,33,"Revision Words",["contest","freeze","impact","object","permit"],2),
    (6,34,"Revision Words",["company","definitely","desperate","jewellery","poisonous"],2),
    (6,35,"Revision Words",["continually","determinedly","diligently","persistently","resolutely"],2),
    (6,36,"Revision Words",["addition","circumference","diameter","division","multiplication"],2),
]

def rule_id(stage, step):
    return f"{stage}-{step}"

def get_rule(rule_id_str):
    """Return rule tuple by 'stage-step' id string."""
    try:
        stage, step = map(int, rule_id_str.split('-'))
        for r in SPELLING_RULES:
            if r[0] == stage and r[1] == step:
                return r
    except Exception:
        pass
    return None

def plannable_rules():
    """Rules that can be selected as current week rule (no Challenge Words)."""
    return [r for r in SPELLING_RULES if r[4] != 1]

def rules_by_stage(stage):
    return [r for r in SPELLING_RULES if r[0] == stage]

def rule_label(r):
    if r is None:
        return "—"
    return f"S{r[0]} Step {r[1]}: {r[2]}"
