"""
WFA Spelling Shed Rules Database
All 216 rules across Stages 1-6.
Each entry: (stage, step, title, words_list, rule_type)
  rule_type: 0=standard, 1=challenge, 2=revision

Challenge Words steps are excluded from the weekly planner current-rule dropdown.
Revision Words steps can be used as revision rules.
"""

SPELLING_RULES = [
    # ── Stage 1 ────────────────────────────────────────────────────────────
    (1,1,"Words ending 'ff','ll','ss','zz','ck'",["puff","bell","grass","buzz","clock"],0),
    (1,2,"/k/ sound as 'k' and 'nk'",["bank","pink","think","kit","mask"],0),
    (1,3,"'tch' trigraph",["catch","fetch","kitchen","switch","hutch"],0),
    (1,4,"Plurals '-s' and '-es'",["flowers","boxes","brushes","lunches","churches"],0),
    (1,5,"Adding '-ing' and '-ed'",["looking","buzzing","jumped","helping","fizzed"],0),
    (1,6,"Prefix 'un-' and suffixes '-er','-est'",["fresher","unhappy","hardest","unfair","unlock"],0),
    (1,7,"Compound words and unstressed vowels",["pocket","balloon","football","bedroom","starfish"],0),
    (1,8,"Digraphs 'ai' and 'oi'",["rain","point","wait","coin","afraid"],0),
    (1,9,"Digraphs 'ay' and 'oy'",["day","play","enjoy","toy","clay"],0),
    (1,10,"Split digraph 'a_e'",["made","take","came","safe","awake"],0),
    (1,11,"Split digraph 'e_e'",["even","complete","these","athlete","theme"],0),
    (1,12,"Split digraph 'i_e'",["five","ride","like","time","slide"],0),
    (1,13,"Split digraph 'o_e'",["home","hope","spoke","joke","bone"],0),
    (1,14,"Split digraph 'u_e'",["June","rude","huge","tune","flute"],0),
    (1,15,"Digraph 'ar'",["car","park","arm","garden","shark"],0),
    (1,16,"Digraph 'ee'",["feel","tree","green","meet","feet"],0),
    (1,17,"'ea' making /ee/",["each","peach","teach","leaf","beak"],0),
    (1,18,"'ea' making /e/",["head","bread","meant","instead","dead"],0),
    (1,19,"Stressed 'er'",["verb","her","term","person","germ"],0),
    (1,20,"Unstressed 'er'",["better","summer","sister","after","winter"],0),
    (1,21,"Digraphs 'ir' and 'ur'",["girl","shirt","turn","hurt","burst"],0),
    (1,22,"'oo' making /oo/",["food","moon","zoo","soon","spoon"],0),
    (1,23,"'oo' making /u/",["book","cook","foot","good","shook"],0),
    (1,24,"'oa' and 'oe' making /oa/",["goat","boat","toe","road","coat"],0),
    (1,25,"'ou' making /ow/",["out","mouth","sound","proud","found"],0),
    (1,26,"'ow' making /ow/ or /oa/",["down","town","own","grow","snow"],0),
    (1,27,"Words ending 'y' /ee/ and 've' /v/",["very","happy","give","have","love"],0),
    (1,28,"Digraphs 'ue' and 'ew'",["blue","clue","true","threw","new"],0),
    (1,29,"'ie' making /igh/",["lie","tie","pie","cried","fried"],0),
    (1,30,"'ie' making /ee/",["chief","thief","piece","field","belief"],0),
    (1,31,"Trigraph 'igh'",["night","light","bright","right","fright"],0),
    (1,32,"Digraph 'or' and trigraph 'ore'",["morning","north","more","score","shore"],0),
    (1,33,"'aw' and 'au' making /or/",["saw","draw","crawl","author","August"],0),
    (1,34,"Trigraphs 'air' and 'ear'",["chair","pair","ear","hear","year"],0),
    (1,35,"'ear' and 'are' making /air/",["bear","wear","bare","care","dare"],0),
    (1,36,"Digraphs 'ph' and 'wh'",["dolphin","elephant","wheel","when","which"],0),
    # ── Stage 2 ────────────────────────────────────────────────────────────
    (2,1,"'dge' making /j/",["badge","bridge","fudge","judge","wedge"],0),
    (2,2,"'ge' making /j/",["change","range","strange","sponge","fringe"],0),
    (2,3,"'g' making /j/",["gem","giant","giraffe","magic","engine"],0),
    (2,4,"'c' making /s/ before e, i, y",["ice","city","fancy","circle","circus"],0),
    (2,5,"'kn' and 'gn' making /n/",["knock","know","knee","knight","gnome"],0),
    (2,6,"Challenge Words",["door","find","kind","child","because"],1),
    (2,7,"'wr' making /r/",["write","wrap","wrong","wren","wrote"],0),
    (2,8,"Words ending 'le'",["table","apple","bottle","little","eagle"],0),
    (2,9,"Words ending 'el'",["camel","tunnel","jewel","travel","towel"],0),
    (2,10,"Words ending 'al'",["metal","capital","animal","equal","local"],0),
    (2,11,"Words ending 'il'",["pencil","fossil","pupil","evil","basil"],0),
    (2,12,"Challenge Words",["wild","climb","most","both","cold"],1),
    (2,13,"'y' making /igh/",["cry","fly","dry","try","shy"],0),
    (2,14,"Adding '-es' to words ending 'y'",["tries","flies","babies","carries","lorries"],0),
    (2,15,"Adding '-ed' to words ending 'y'",["copied","replied","spied","applied","supplied"],0),
    (2,16,"Adding '-er' and '-est' to words ending 'y'",["happier","happiest","tidier","tidiest","funnier"],0),
    (2,17,"Adding '-ing' to words ending 'e'",["hiking","smiling","writing","hoping","caring"],0),
    (2,18,"Challenge Words",["every","great","break","beautiful","pretty"],1),
    (2,19,"Adding '-er','-est','-ed' to words ending 'e'",["nicer","safer","hoped","loved","largest"],0),
    (2,20,"Adding '-ing' to single syllable words",["patting","running","hopping","sitting","dropping"],0),
    (2,21,"Adding '-ed' to single syllable words",["patted","hummed","dropped","clapped","dragged"],0),
    (2,22,"'a' making /or/",["all","ball","walk","call","always"],0),
    (2,23,"'o' making /u/",["other","mother","some","money","done"],0),
    (2,24,"Challenge Words",["last","father","class","path","bath"],1),
    (2,25,"'ey' making /ee/",["key","donkey","monkey","valley","journey"],0),
    (2,26,"'a' making /o/",["want","watch","wander","quality","squash"],0),
    (2,27,"'or' and 'ar' making /er/ or /or/",["word","work","world","warm","war"],0),
    (2,28,"'si' and 's' making /zh/",["television","measure","pleasure","vision","leisure"],0),
    (2,29,"Suffixes '-ment' and '-ness'",["enjoyment","agreement","darkness","sadness","kindness"],0),
    (2,30,"Suffixes '-ful', '-less' and '-ly'",["careful","thankful","boldly","happily","hopeless"],0),
    (2,31,"Homophones",["there","their","they're","here","hear","see","sea"],0),
    (2,32,"Homophones and near homophones",["quiet","quite","bare","bear","sun","son"],0),
    (2,33,"Words ending '-tion'",["station","fiction","motion","action","fraction"],0),
    (2,34,"Apostrophe for contraction",["can't","didn't","hasn't","couldn't","wasn't"],0),
    (2,35,"Apostrophe for possession",["Megan's","Sam's","child's","boy's","dog's"],0),
    (2,36,"Challenge Words",["whole","any","many","clothes","people"],1),
    # ── Stage 3 ────────────────────────────────────────────────────────────
    (3,1,"'ou' making /ow/",["mouth","sprout","sound","hound","proud"],0),
    (3,2,"'ou' making /u/",["touch","double","country","trouble","young"],0),
    (3,3,"'y' making /i/",["symbol","gym","myth","pyramid","mystery"],0),
    (3,4,"Words ending '-sure'",["treasure","measure","leisure","pleasure","pressure"],0),
    (3,5,"Words ending '-ture'",["adventure","future","picture","nature","creature"],0),
    (3,6,"Challenge Words",["actual","bicycle","island","often","popular"],1),
    (3,7,"Prefix 're-'",["redo","return","refresh","replay","reappear"],0),
    (3,8,"Prefix 'dis-'",["disappoint","disobey","disappear","disable","disagree"],0),
    (3,9,"Prefix 'mis-'",["mistake","mislead","misbehave","misplace","misread"],0),
    (3,10,"'-ing','-er','-ed' on multisyllabic (stressed)",["forgetting","forgotten","beginning","propelled","preferred"],0),
    (3,11,"'-ing','-en','-ed' on multisyllabic (unstressed)",["developing","developed","limiting","covering","listened"],0),
    (3,12,"Challenge Words",["centre","disappear","heart","minute","notice"],1),
    (3,13,"Digraph 'ai' and tetragraph 'aigh'",["straight","strainer","waist","snail","painter"],0),
    (3,14,"Digraph 'ei' and tetragraph 'eigh'",["freight","vein","weigh","eight","reign"],0),
    (3,15,"'ey' making /ai/",["obey","prey","they","convey","grey"],0),
    (3,16,"Suffix '-ly'",["calmly","exactly","bravely","boldly","quickly"],0),
    (3,17,"Homophones",["great","grate","meet","meat","main","mane"],0),
    (3,18,"Challenge Words",["build","beautiful","great","break","steak"],1),
    (3,19,"Words ending '-al'",["arrival","comical","magical","national","tropical"],0),
    (3,20,"Words ending '-le'",["battle","humble","terrible","possible","capable"],0),
    (3,21,"'-ly' where base ends 'le'",["gently","simply","humbly","nobly","terribly"],0),
    (3,22,"'-ly' where base ends '-ic'",["basically","frantically","logically","tragically","magically"],0),
    (3,23,"'-ly' exceptions",["truly","slyly","fully","duly","shyly"],0),
    (3,24,"Challenge Words",["address","mention","occasionally","certainly","probably"],1),
    (3,25,"Suffix '-er' (person who)",["teacher","stretcher","catcher","butcher","watcher"],0),
    (3,26,"'ch' making /k/",["scheme","chorus","echo","character","school"],0),
    (3,27,"Words ending '-gue' and '-que'",["vague","league","plague","antique","unique"],0),
    (3,28,"'sc' making /s/",["science","scene","scissors","fascinate","descend"],0),
    (3,29,"Homophones",["ball","bawl","break","brake","fair","fare"],0),
    (3,30,"Challenge Words",["accidentally","breathe","century","consider","guard"],1),
    (3,31,"Words ending '-sion' /zhun/",["vision","confusion","division","invasion","decision"],0),
    (3,32,"Challenge Words",["special","strange","difficult","important","length"],1),
    (3,33,"Revision Words",["exactly","bravely","pleasure","island","decide"],2),
    (3,34,"Revision Words",["freight","hourly","scented","descend","plaque"],2),
    (3,35,"Revision Words",["teacher","scheme","mention","crescent","eighteen"],2),
    (3,36,"Revision Words",["disappear","reaction","committed","capable","confusion"],2),
    # ── Stage 4 ────────────────────────────────────────────────────────────
    (4,1,"Homophones",["accept","except","peace","piece","plain","plane"],0),
    (4,2,"Prefix 'in-' (not)",["inability","inactive","incorrect","invisible","insecure"],0),
    (4,3,"Prefixes 'il-','im-','ir-'",["illegal","immature","impossible","irregular","irresponsible"],0),
    (4,4,"Prefix 'sub-'",["subdivide","submarine","submerge","subtitle","subway"],0),
    (4,5,"Prefix 'inter-'",["interact","intercity","intercom","interfere","international"],0),
    (4,6,"Challenge Words",["strength","grammar","calendar","women","believe"],1),
    (4,7,"Words ending '-ation' (from -ate verbs)",["information","sensation","preparation","vibration","decoration"],0),
    (4,8,"Words ending '-ation' (other verbs)",["adoration","admiration","coronation","observation","generation"],0),
    (4,9,"Words ending '-ly'",["sadly","completely","wildly","bravely","gently"],0),
    (4,10,"Words ending '-lly'",["usually","finally","beautifully","thoughtfully","carefully"],0),
    (4,11,"'ch' making /sh/ (French origin)",["chef","chalet","machine","brochure","chandelier"],0),
    (4,12,"Challenge Words",["favourite","complete","continue","experiment","February"],1),
    (4,13,"Words ending '-sion' /zhun/",["expansion","extension","comprehension","tension","suspension"],0),
    (4,14,"Words ending '-ous'",["poisonous","dangerous","mountainous","marvellous","enormous"],0),
    (4,15,"Words ending '-ous' (ge retained)",["courageous","outrageous","nervous","famous","adventurous"],0),
    (4,16,"Suffix added to words ending 'y'",["merriment","happiness","plentiful","penniless","prettiest"],0),
    (4,17,"Words ending '-ious' and '-eous'",["serious","obvious","curious","hideous","spontaneous"],0),
    (4,18,"Challenge Words",["extreme","although","breath","caught","different"],1),
    (4,19,"'au' making /or/",["automatic","August","launch","haul","astronaut"],0),
    (4,20,"Words ending '-tion'",["invention","injection","action","hesitation","completion"],0),
    (4,21,"Words ending '-sion' /shun/",["expression","discussion","confession","permission","impression"],0),
    (4,22,"Words ending '-cian'",["musician","magician","electrician","politician","mathematician"],0),
    (4,23,"Adverbs of manner",["reluctantly","quickly","generously","curiously","furiously"],0),
    (4,24,"Challenge Words",["surprise","separate","height","potatoes","through"],1),
    (4,25,"Homophones",["scene","seen","affect","effect"],0),
    (4,26,"'c' before i and e (soft c)",["circle","century","circus","princess","celebrate"],0),
    (4,27,"Word roots 'sol' and 'real'",["solve","insoluble","real","reality","solution"],0),
    (4,28,"Word roots 'phon' and 'sign'",["signal","telephone","microphone","homophone","phonics"],0),
    (4,29,"Prefixes 'super-','anti-','auto-'",["supermarket","superhero","antiseptic","anticlockwise","autograph"],0),
    (4,30,"Prefix 'bi-' (two)",["bicycle","biplane","biped","biannual","bilingual"],0),
    (4,31,"Challenge Words",["guide","possess","accident","occasion","Wednesday"],1),
    (4,32,"Plural possessive apostrophes",["girls'","boys'","babies'","children's","men's"],0),
    (4,33,"Revision Words",["expression","musician","reluctantly","scene","circle"],2),
    (4,34,"Revision Words",["incorrect","illegible","international","believe","wildly"],2),
    (4,35,"Revision Words",["gently","separate","affect","unexpectedly","potatoes"],2),
    (4,36,"Revision Words",["disappear","specifically","reaction","committed","capable"],2),
    # ── Stage 5 ────────────────────────────────────────────────────────────
    (5,1,"Words ending '-tious' and '-ious'",["ambitious","amphibious","fictitious","infectious","notorious"],0),
    (5,2,"Words ending '-cious'",["atrocious","delicious","ferocious","gracious","suspicious"],0),
    (5,3,"Words ending '-cial'",["artificial","beneficial","crucial","facial","official"],0),
    (5,4,"Words ending '-tial'",["circumstantial","confidential","essential","influential","potential"],0),
    (5,5,"Words ending '-cial' and '-tial'",["commercial","financial","initial","palatial","spatial"],0),
    (5,6,"Challenge Words",["appreciate","cemetery","environment","sufficient","vegetable"],1),
    (5,7,"Words ending '-ant'",["abundant","brilliant","constant","elegant","tolerant"],0),
    (5,8,"Words ending '-ance' and '-ancy'",["abundance","brilliance","elegance","extravagance","tolerance"],0),
    (5,9,"Words ending '-ent' and '-ence'",["competence","confidence","eloquence","intelligence","frequent"],0),
    (5,10,"Words ending '-able' and '-ible'",["comfortable","dependable","enjoyable","horrible","possible"],0),
    (5,11,"Words ending '-ably' and '-ibly'",["comfortably","dependably","horribly","incredibly","terribly"],0),
    (5,12,"Challenge Words",["accommodate","available","controversy","marvellous","sincerely"],1),
    (5,13,"'-able' where root 'e' remains",["agreeable","changeable","knowledgeable","noticeable","replaceable"],0),
    (5,14,"Adverbs of time",["afterwards","eventually","immediately","previously","recently"],0),
    (5,15,"Suffixes where base ends 'fer'",["conferring","difference","preference","preferred","referring"],0),
    (5,16,"Silent first letters",["knife","knight","knuckle","wreath","wreckage"],0),
    (5,17,"Silent letters",["ascend","doubt","island","solemn","thistle"],0),
    (5,18,"Challenge Words",["ancient","amateur","awkward","criticise","equipment"],1),
    (5,19,"'ie' after 'c'",["society","deficient","efficient","science","species"],0),
    (5,20,"'ei' making /ee/",["caffeine","conceive","deceive","perceive","receive"],0),
    (5,21,"'ough' making /or/",["afterthought","bought","brought","fought","thought"],0),
    (5,22,"Words containing 'ough'",["although","bough","dough","enough","plough"],0),
    (5,23,"Adverbs of possibility and frequency",["certainly","definitely","frequently","occasionally","probably"],0),
    (5,24,"Challenge Words",["communicate","conscience","nuisance","queue","restaurant"],1),
    (5,25,"Homophones / near homophones",["advice","advise","licence","license","practice"],0),
    (5,26,"Homophones",["aisle","isle","allowed","aloud","altar"],0),
    (5,27,"Homophones",["bridal","bridle","heard","herd","morning"],0),
    (5,28,"Homophones / near homophones",["dessert","desert","who's"],0),
    (5,29,"Homophones / near homophones",["cereal","serial","complement","compliment","stationary","stationery"],0),
    (5,30,"Challenge Words",["achieve","apparent","bargain","bruise","community"],1),
    (5,31,"Words with hyphens",["co-author","co-operate","re-educate","re-enter","re-evaluate"],0),
    (5,32,"Challenge Words",["afterwards","amateur","ancient","changeable","knight"],1),
    (5,33,"Revision Words",["accompany","achieve","advice","affect","aisle"],2),
    (5,34,"Revision Words",["ascend","awkward","conscience","dough","probably"],2),
    (5,35,"Revision Words",["ball","bawl","break","brake","fair"],2),
    (5,36,"Revision Words",["aloud","community","complement","desert","device"],2),
    # ── Stage 6 ────────────────────────────────────────────────────────────
    (6,1,"Short /i/ spelled 'y'",["antonym","crystal","lyrics","mystery","symbol"],0),
    (6,2,"Long /igh/ spelled 'y'",["apply","hygiene","hyphen","identify","multiply"],0),
    (6,3,"Challenge Words",["ancient","cemetery","criticise","equipped","government"],1),
    (6,4,"'cial' /shul/ after vowel",["antisocial","artificial","facial","official","special"],0),
    (6,5,"'tial' /shul/",["confidential","essential","influential","martial","potential"],0),
    (6,6,"Challenge Words",["amateur","category","correspond","environment","frequently"],1),
    (6,7,"Challenge Words",["appreciate","communicate","exaggerate","harass","marvellous"],1),
    (6,8,"/oa/ spelled 'ou' or 'ow'",["blown","mould","shoulder","soul","window"],0),
    (6,9,"Soft c spelled 'ce'",["celebrate","cemetery","certificate","deceased","December"],0),
    (6,10,"Challenge Words",["apparent","committee","guarantee","parliament","recommend"],1),
    (6,11,"/f/ spelled 'ph'",["alphabet","dolphin","elephant","graph","phone"],0),
    (6,12,"Challenge Words",["according","awkward","conscious","dictionary","familiar"],1),
    (6,13,"Suffix '-ably'",["adorably","believably","comfortably","noticeably","reasonably"],0),
    (6,14,"Suffix '-ible'",["forcible","horrible","incredible","possible","responsible"],0),
    (6,15,"Challenge Words",["attached","desperate","excellent","hindrance","mischievous"],1),
    (6,16,"Suffix '-ibly'",["forcibly","horribly","incredibly","possibly","responsibly"],0),
    (6,17,"Words ending '-ent' and '-ence'",["convenience","convenient","difference","different","excellence"],0),
    (6,18,"Challenge Words",["accommodate","available","competition","determined","existence"],1),
    (6,19,"Challenge Words",["aggressive","bruise","embarrass","interrupt","pronunciation"],1),
    (6,20,"Words ending '-er','-or','-ar'",["calendar","computer","customer","radiator","shoulder"],0),
    (6,21,"Challenge Words",["achieve","bargain","controversy","disastrous","foreign"],1),
    (6,22,"Words beginning 'acc-'",["accentuate","access","accommodate","accompany","accomplish"],0),
    (6,23,"Prefixes 'dis-','un-','over-','im-'",["disappointed","dissatisfied","impatient","overreact","unnecessary"],0),
    (6,24,"Challenge Words",["accompany","average","conscience","immediately","necessary"],1),
    (6,25,"Words from other languages",["ballet","blizzard","bungalow","gymkhana","pyjamas"],0),
    (6,26,"Grammar Vocabulary 1",["adverb","bracket","clause","cohesion","determiner"],0),
    (6,27,"Grammar Vocabulary 2",["active","antonym","colon","ellipsis","hyphen"],0),
    (6,28,"Prefix 'over-'",["overbalance","overcoat","overlooked","overreact","overturned"],0),
    (6,29,"Suffix '-ful'",["beautiful","doubtful","faithful","fearful","merciful"],0),
    (6,30,"Adjectives: settings",["bustling","majestic","picturesque","sinister","tranquil"],0),
    (6,31,"Adjectives: feelings",["apprehensive","despondent","euphoric","incensed","jittery"],0),
    (6,32,"Adjectives: characters",["amiable","courageous","disagreeable","gargantuan","valiant"],0),
    (6,33,"Revision Words",["contest","freeze","impact","object","permit"],2),
    (6,34,"Revision Words",["company","definitely","desperate","jewellery","poisonous"],2),
    (6,35,"Revision Words",["continually","determinedly","diligently","persistently","resolutely"],2),
    (6,36,"Revision Words",["addition","circumference","diameter","division","multiplication"],2),
]

def rule_id(stage, step):
    return f"{stage}-{step}"

def get_rule(rule_id_str):
    """Return rule tuple by 'stage-step' id string."""
    try:
        stage, step = map(int, rule_id_str.split('-'))
        for r in SPELLING_RULES:
            if r[0] == stage and r[1] == step:
                return r
    except Exception:
        pass
    return None

def plannable_rules():
    """Rules that can be selected as current week rule (no Challenge Words)."""
    return [r for r in SPELLING_RULES if r[4] == 0]

def rules_by_stage(stage):
    return [r for r in SPELLING_RULES if r[0] == stage]

def rule_label(r):
    if r is None:
        return "—"
    return f"S{r[0]} Step {r[1]}: {r[2]}"

RULE_EXPLANATIONS = {
    '1-1': 'When a short vowel sound is followed by an /f/, /l/, /s/ or /z/ sound at the end of a word, we usually double the consonant (e.g. puff, bell, kiss, buzz). The /k/ sound at the end of a short-vowel word is always spelled \'ck\' (e.g. clock, back).',
    '1-2': 'The /k/ sound can be spelled with a \'k\', especially before \'e\', \'i\' or a consonant (e.g. kit, mask, skin). The \'nk\' pattern makes a blended /nk/ sound, as in bank or pink.',
    '1-3': 'A trigraph is three letters that together make one sound. The letters \'t\', \'c\' and \'h\' make the /ch/ sound and this pattern is used after a short vowel (e.g. catch, fetch, hutch).',
    '1-4': 'To make most words mean more than one (plural), we add \'-s\' (e.g. cars, boats). When a word ends in \'s\', \'x\', \'sh\', \'ch\' or \'z\', we add \'-es\' instead (e.g. boxes, brushes, churches).',
    '1-5': 'A suffix is letters added to the end of a word to change its meaning. \'-ing\' shows something is happening now (e.g. buzzing, jumping) and \'-ed\' shows it has already happened (e.g. buzzed, jumped).',
    '1-6': 'A prefix is letters added to the start of a word to change its meaning. \'un-\' means \'not\' or \'do the opposite\' (e.g. unhappy, undo). The suffixes \'-er\' and \'-est\' are added to adjectives to compare things (e.g. fresher, hardest).',
    '1-7': 'A compound word is made by joining two smaller words together (e.g. football, sunset, bedroom). Some words also contain an unstressed vowel — a vowel that is difficult to hear clearly when the word is said aloud (e.g. the \'o\' in carrot, the first \'o\' in balloon).',
    '1-8': 'A digraph is two letters that together make one sound. \'ai\' makes the /ay/ sound (e.g. rain, train) and \'oi\' makes the /oy/ sound (e.g. coin, point). Both digraphs usually appear in the middle of a word.',
    '1-9': 'The digraph \'ay\' makes the /ay/ sound (e.g. day, play) and \'oy\' makes the /oy/ sound (e.g. toy, enjoy). Unlike \'ai\' and \'oi\', these digraphs usually appear at the end of a word.',
    '1-10': 'A split digraph is when two vowels work together to make a long vowel sound but have a consonant between them. The \'a_e\' pattern makes a long /ay/ sound — the \'e\' at the end is silent but changes the vowel sound (e.g. make, came, same).',
    '1-11': 'The split digraph \'e_e\' makes a long /ee/ sound. The silent \'e\' at the end makes the first \'e\' say its name (e.g. these, theme, complete).',
    '1-12': 'The split digraph \'i_e\' makes a long /igh/ sound. The silent \'e\' at the end makes the \'i\' say its name (e.g. ride, like, time).',
    '1-13': 'The split digraph \'o_e\' makes a long /oa/ sound. The silent \'e\' at the end makes the \'o\' say its name (e.g. home, hope, spoke).',
    '1-14': 'The split digraph \'u_e\' makes a long /yoo/ or /oo/ sound. The silent \'e\' at the end changes the sound of the \'u\' (e.g. tune, rude, flute).',
    '1-15': 'The digraph \'ar\' makes a long /ar/ sound, as in car or park. The letters \'a\' and \'r\' work together to make this sound.',
    '1-16': 'The digraph \'ee\' always makes a long /ee/ sound (e.g. feel, tree, meet). Two \'e\' letters together consistently make this sound.',
    '1-17': 'The digraph \'ea\' can make a long /ee/ sound (e.g. reach, teach, leaf). The same two letters can also make a different sound, so it is useful to learn which words follow this pattern.',
    '1-18': 'In some words, the digraph \'ea\' makes a short /e/ sound rather than a long /ee/ sound (e.g. head, bread, dead). These words need to be learned carefully as they do not follow the more common pattern.',
    '1-19': 'When \'er\' is stressed — said with more emphasis — it makes a clear /er/ sound that you can hear distinctly (e.g. her, verb, term). The stress means the sound stands out clearly.',
    '1-20': 'When \'er\' is unstressed, it makes a quieter /uh/ sound at the end of a word (e.g. summer, sister, river). This weak vowel sound is called a schwa and is very common in English.',
    '1-21': 'The digraphs \'ir\' and \'ur\' both make the same /er/ sound (e.g. girl, first, turn, hurt). It is important to learn which spelling each individual word uses.',
    '1-22': 'The digraph \'oo\' can make a long /oo/ sound as in moon or food. This is the longer, stronger version of the \'oo\' sound.',
    '1-23': 'The digraph \'oo\' can also make a shorter /u/ sound as in book or cook. The same two letters make two different sounds, so these words need to be learned as a group.',
    '1-24': 'The digraphs \'oa\' and \'oe\' both make a long /oa/ sound (e.g. goat, road, toe). \'oa\' usually appears in the middle of a word while \'oe\' usually appears at the end.',
    '1-25': 'The digraph \'ou\' can make an /ow/ sound as in out or sound. The letters \'o\' and \'u\' together make this sound in many common words (e.g. around, found, proud).',
    '1-26': 'The digraph \'ow\' can make two different sounds — an /ow/ sound (e.g. down, town) or an /oa/ sound (e.g. snow, grow, blow). You need to learn which sound each word uses.',
    '1-27': 'Many words end in \'y\' making an /ee/ sound (e.g. very, happy, funny). In English, the /v/ sound at the end of a word is always spelled \'ve\' — English words never end in a bare \'v\' (e.g. give, have, love).',
    '1-28': 'The digraphs \'ue\' and \'ew\' both make a /yoo/ or /oo/ sound (e.g. clue, true, new, drew). These patterns are usually found at the end of a word.',
    '1-29': 'The digraph \'ie\' can make a long /igh/ sound at the end of a word (e.g. lie, pie, tie). When \'-ed\' is added to words ending in \'y\', the \'y\' changes to \'i\' before the suffix, which also produces this pattern (e.g. fry → fried, dry → dried).',
    '1-30': 'The digraph \'ie\' can also make a long /ee/ sound (e.g. chief, thief, piece, field). The same letters can make different sounds, so these words need to be learned as a group.',
    '1-31': 'The trigraph \'igh\' — three letters making one sound — makes a long /igh/ sound (e.g. night, light, bright). The \'gh\' in this pattern is always silent.',
    '1-32': 'The digraph \'or\' makes an /or/ sound (e.g. north, morning, torn) and the trigraph \'ore\' makes the same sound, usually at the end of a word (e.g. more, shore, before).',
    '1-33': 'The digraphs \'aw\' and \'au\' both make an /or/ sound (e.g. saw, crawl, author, August). \'aw\' often appears at the end of a word or before a consonant, while \'au\' usually appears in the middle.',
    '1-34': 'The trigraph \'air\' makes an /air/ sound (e.g. chair, pair, fairy) and the trigraph \'ear\' makes an /ear/ sound (e.g. ear, hear, year). Both patterns use three letters working together to make one sound.',
    '1-35': 'In some words, \'ear\' and \'are\' make an /air/ sound rather than their more common sounds (e.g. bear, wear, bare, dare, care). These are less common patterns and need to be learned carefully.',
    '1-36': 'The digraph \'ph\' makes an /f/ sound and comes from Greek words (e.g. dolphin, elephant, phonics). The digraph \'wh\' usually makes a /w/ sound (e.g. wheel, when, which, why).',
    '2-1': 'The three letters \'d\', \'g\' and \'e\' together make a /j/ sound (e.g. badge, bridge, fudge). This pattern is used after a short vowel sound and never appears at the start of a word.',
    '2-2': 'The letters \'ge\' make a /j/ sound at the end of a word or before a consonant (e.g. change, range, strange). This is different from \'dge\', which follows immediately after a short vowel.',
    '2-3': 'Before the letters \'e\', \'i\' or \'y\', the letter \'g\' can make a soft /j/ sound instead of its usual hard /g/ sound (e.g. gem, giant, giraffe, engine). This is called a \'soft g\'.',
    '2-4': 'Before the letters \'e\', \'i\' or \'y\', the letter \'c\' makes a soft /s/ sound instead of its usual hard /k/ sound (e.g. ice, city, fancy, circle). This is called a \'soft c\'.',
    '2-5': 'In some words, the first letter of \'kn\' or \'gn\' is silent — only the \'n\' is sounded (e.g. knock, know, gnome, gnat). These silent letters come from older forms of English.',
    '2-6': 'These words have irregular spelling patterns. The letters may make unexpected sounds or follow unusual rules, so they need to be learned carefully (e.g. door, floor, find, kind, children, because).',
    '2-7': 'At the start of some words, \'wr\' makes a /r/ sound — the \'w\' is completely silent (e.g. write, wrap, wrong, wren). This pattern comes from older English and has stayed in the spelling of these words.',
    '2-8': 'Many words end in \'le\' making an /ul/ sound (e.g. table, apple, little, bubble). The \'le\' forms a soft, unstressed syllable at the end of the word.',
    '2-9': 'Some words end in \'el\' making the same /ul/ sound as \'le\' endings (e.g. camel, tunnel, jewel, towel). These words must be learned individually since the sound is identical to \'le\' endings.',
    '2-10': 'Some words end in \'al\' making an /ul/ sound (e.g. metal, capital, animal, local). This sounds the same as \'le\' and \'el\' endings but uses different letters — these words must be learned.',
    '2-11': 'Some words end in \'il\' making an /ul/ sound (e.g. pencil, fossil, pupil, basil). Like \'le\', \'el\' and \'al\', the ending sounds the same but has a different spelling that must be learned.',
    '2-12': 'These words do not follow common spelling rules and include unexpected patterns. They are high-frequency words worth learning carefully (e.g. wild, climb, most, both, old, cold, told).',
    '2-13': 'At the end of a short, single-syllable word, \'y\' makes a long /igh/ sound (e.g. cry, fly, try, shy). This is different from words where \'y\' makes an /ee/ sound at the end of longer words.',
    '2-14': 'When a word ends in a consonant followed by \'y\', the \'y\' changes to \'i\' before adding \'-es\' to make it plural or to add a verb ending (e.g. fly → flies, baby → babies, carry → carries).',
    '2-15': 'When a word ends in a consonant followed by \'y\', the \'y\' changes to \'i\' before adding \'-ed\' (e.g. copy → copied, reply → replied, spy → spied). The \'y\' is never kept before \'-ed\'.',
    '2-16': 'When a word ends in a consonant followed by \'y\', the \'y\' changes to \'i\' before adding \'-er\' or \'-est\' (e.g. happy → happier → happiest, tidy → tidier → tidiest).',
    '2-17': 'When a word ends in a silent \'e\', we remove the \'e\' before adding \'-ing\' (e.g. hike → hiking, smile → smiling, write → writing, surprise → surprising).',
    '2-18': 'These words contain irregular or unusual patterns and do not follow common spelling rules. They are frequently used words worth practising carefully (e.g. every, even, beautiful, break, steak).',
    '2-19': 'When a word ends in a silent \'e\', the \'e\' is removed before adding \'-er\', \'-est\' or \'-ed\' (e.g. nice → nicer → nicest, hope → hoped, large → largest).',
    '2-20': 'When a single-syllable word has a short vowel sound and ends in a single consonant, we double that consonant before adding \'-ing\' (e.g. run → running, hop → hopping, sit → sitting). This keeps the short vowel sound.',
    '2-21': 'When a single-syllable word has a short vowel sound and ends in a single consonant, we double that consonant before adding \'-ed\' (e.g. pat → patted, drum → drummed, drop → dropped). This keeps the short vowel sound.',
    '2-22': 'In some words, the letter \'a\' makes an /or/ sound rather than its usual short or long sound (e.g. all, ball, walk, call, always). This usually happens when \'a\' is followed by \'ll\' or \'lk\'.',
    '2-23': 'In some common words, the letter \'o\' makes a short /u/ sound instead of its usual sounds (e.g. other, mother, some, money, done). These are high-frequency words worth learning as a group.',
    '2-24': 'These words contain irregular patterns or unusual pronunciations and need to be learned carefully. They are frequently used words that do not fully follow standard spelling rules (e.g. last, father, class, path, bath).',
    '2-25': 'The digraph \'ey\' usually makes an /ay/ sound, but in these words it makes an /ee/ sound (e.g. key, monkey, donkey, journey, valley). These words mostly appear at the end of the word.',
    '2-26': 'In some words, particularly after the letter \'w\', the letter \'a\' makes a short /o/ sound (e.g. want, watch, wander, quality, squash). This is an irregular pattern that needs to be learned.',
    '2-27': 'After the letter \'w\', the patterns \'or\' and \'ar\' can make an /er/ sound rather than their usual sounds (e.g. word, work, world, warm, war). These words need to be learned as a group.',
    '2-28': 'In some words, \'si\' or \'s\' between two vowels makes a soft /zh/ sound — like the \'s\' in treasure or the \'si\' in television. This is softer and more buzzing than the usual /s/ sound.',
    '2-29': 'The suffix \'-ment\' turns a verb into a noun meaning the result of an action (e.g. enjoy → enjoyment, adjust → adjustment). The suffix \'-ness\' turns an adjective into a noun meaning a state or quality (e.g. dark → darkness, kind → kindness).',
    '2-30': '\'-ful\' means full of something (e.g. careful, thankful). \'-less\' means without something (e.g. hopeless, spotless). \'-ly\' turns an adjective into an adverb — a word describing how something is done (e.g. bold → boldly, happy → happily).',
    '2-31': 'Homophones are words that sound exactly the same but have different spellings and different meanings (e.g. there/their, here/hear, see/sea, too/two). Understanding the meaning helps you choose the correct spelling.',
    '2-32': 'Homophones sound exactly the same but are spelled differently (e.g. bare/bear, be/bee). Near homophones sound very similar but not identical (e.g. quiet/quite, sun/son). Meaning helps you decide which word to use.',
    '2-33': 'The suffix \'-tion\' turns a verb into a noun and makes a /shun/ sound (e.g. act → action, inject → injection, compete → competition). This is one of the most common ways to make a noun from a verb in English.',
    '2-34': 'A contraction is when two words are shortened into one, with an apostrophe marking where letters have been left out (e.g. can\'t = cannot, didn\'t = did not, I\'ll = I will). The apostrophe always goes exactly where the missing letters were.',
    '2-35': 'An apostrophe followed by \'s\' shows that something belongs to someone (e.g. Megan\'s bag, the dog\'s lead, the child\'s coat). The apostrophe and \'s\' always go directly after the name or noun of the owner.',
    '2-36': 'These words contain irregular or less common spelling patterns that need to be learned carefully. They are frequently used words worth knowing well (e.g. whole, any, many, clothes, busy, people, again, half, hour).',
    '3-1': 'The digraph \'ou\' can make an /ow/ sound as in mouth, sound and proud. This is one of the most common spellings for the /ow/ sound in English.',
    '3-2': 'The digraph \'ou\' can also make a short /u/ sound (e.g. touch, double, young, country). The same letters make different sounds in different words, so these need to be learned carefully.',
    '3-3': 'In words with Greek origins, the letter \'y\' is used in the middle of a word to make a short /i/ sound (e.g. symbol, gym, myth, mystery, pyramid). This is the same sound as the \'i\' in \'it\' or \'him\'.',
    '3-4': 'The ending \'-sure\' makes a /zhur/ sound, where the \'s\' makes a soft, buzzing sound rather than its usual /s/ sound (e.g. treasure, measure, leisure, pressure). These words need to be learned as a group.',
    '3-5': 'The ending \'-ture\' makes a /cher/ sound — the \'t\' and \'ure\' blend together and do not sound like their individual letters (e.g. picture, nature, future, adventure, fracture).',
    '3-6': 'These words contain unusual or irregular patterns and do not follow common spelling rules. They include frequently used words worth practising carefully (e.g. actual, bicycle, island, often, popular).',
    '3-7': 'The prefix \'re-\' means \'again\' or \'back\' (e.g. redo = do again, return = go back, replay = play again). Adding \'re-\' to the start of a word changes its meaning without changing the spelling of the base word.',
    '3-8': 'The prefix \'dis-\' means \'not\', \'opposite of\' or \'away from\' (e.g. disappear = not appear, disagree = not agree, dislocate = move away from its place). Adding \'dis-\' reverses or negates the meaning of the base word.',
    '3-9': 'The prefix \'mis-\' means \'badly\' or \'wrongly\' (e.g. misbehave = behave badly, misread = read incorrectly, misplace = put in the wrong place). Adding \'mis-\' suggests the action was done the wrong way.',
    '3-10': 'When a word has more than one syllable and the final syllable is stressed with a short vowel and single consonant, that consonant is doubled before adding a suffix (e.g. forget → forgetting, propel → propelled, prefer → preferred). If the stress falls elsewhere, the consonant is not doubled.',
    '3-11': 'When the final syllable of a word is not stressed, the final consonant is not doubled before adding a suffix (e.g. garden → gardening, cover → covered, listen → listened). This is the opposite of the rule for stressed final syllables.',
    '3-12': 'These words contain unusual spelling patterns and do not always follow common rules. They are important and frequently used words worth practising carefully (e.g. centre, disappear, heart, minute, notice, therefore).',
    '3-13': 'The digraph \'ai\' makes an /ay/ sound in the middle of words (e.g. waist, snail, chained). The tetragraph \'aigh\' — four letters making one sound — also makes an /ay/ sound (e.g. straight). These are less common patterns for the /ay/ sound.',
    '3-14': 'The digraph \'ei\' and tetragraph \'eigh\' both make an /ay/ sound in these words (e.g. vein, freight, eight, weigh, reign). These are unusual spellings for the /ay/ sound and need to be learned as a group.',
    '3-15': 'The digraph \'ey\' usually makes an /ee/ sound, but in these words it makes an /ay/ sound (e.g. they, obey, prey, grey, convey). These words need to be learned individually.',
    '3-16': 'The suffix \'-ly\' is added to an adjective to make an adverb — a word describing how something is done (e.g. calm → calmly, exact → exactly, brave → bravely). When the base word ends in \'y\', the \'y\' usually changes to \'i\' before adding \'-ly\' (e.g. bold → boldly).',
    '3-17': 'Homophones are words that sound exactly the same but have different spellings and meanings (e.g. great/grate, meet/meat, main/mane, grown/groan). Understanding the meaning of a word in context is the key to choosing the right spelling.',
    '3-18': 'These words contain irregular or unusual patterns and do not follow common spelling rules. They are frequently used words worth learning carefully (e.g. build, beautiful, break, steak, after, fast).',
    '3-19': 'The ending \'-al\' makes an /ul/ sound in many adjectives and nouns (e.g. arrival, magical, emotional, national, tropical). These are mostly longer, more formal words where \'-al\' has become part of the word\'s structure.',
    '3-20': 'The ending \'-le\' makes an /ul/ sound at the end of words (e.g. battle, humble, possible, capable, terrible). Learning the spelling of the whole word — including whether it ends in \'-le\', \'-al\', or \'-el\' — is the most reliable approach.',
    '3-21': 'When a word ends in \'-le\', the \'le\' is dropped before adding \'-ly\' (e.g. gentle → gently, simple → simply, humble → humbly). This is an exception to the usual rule of just adding \'-ly\' without changing the base word.',
    '3-22': 'When a word ends in \'-ic\', we add \'-ally\' rather than just \'-ly\' to make an adverb (e.g. basic → basically, magic → magically, tragic → tragically). The \'-al-\' is inserted between the base word and \'-ly\'.',
    '3-23': 'Some adverbs ending in \'-ly\' are exceptions to the usual rules (e.g. true → truly, full → fully, due → duly, whole → wholly). For example, \'truly\' drops the \'e\' while \'shyly\' keeps the \'y\' rather than changing it to \'i\'. These need to be learned individually.',
    '3-24': 'These words include irregular patterns, silent letters or unexpected pronunciations. They are commonly used words worth memorising carefully (e.g. address, mention, occasionally, certainly, probably).',
    '3-25': 'The suffix \'-er\' is added to a verb to make a noun meaning a person who does that action (e.g. teach → teacher, catch → catcher, preach → preacher). The spelling of the base word is preserved before adding \'-er\'.',
    '3-26': 'In words with Greek origins, \'ch\' makes a /k/ sound instead of its usual /ch/ sound (e.g. school, echo, character, chorus, stomach). These words need to be learned as the \'ch\' behaves unexpectedly.',
    '3-27': 'The endings \'-gue\' and \'-que\' come from French and always end in a silent \'e\'. The \'gue\' pattern makes a hard /g/ sound (e.g. vague, league, plague) and \'que\' makes a /k/ sound (e.g. antique, unique, grotesque).',
    '3-28': 'In some words, \'sc\' before \'e\', \'i\' or \'y\' makes a soft /s/ sound — the \'c\' does not add a separate sound (e.g. scene, science, scissors, descend, fascinate). Without the context of \'sc\', these words might look as though they have a /sk/ sound.',
    '3-29': 'Homophones are words that sound exactly the same but have different meanings and spellings (e.g. ball/bawl, brake/break, mail/male, fair/fare, berry/bury). The meaning in the sentence tells you which spelling to use.',
    '3-30': 'These words contain unusual spelling patterns or are commonly misspelled. They include frequently used words worth memorising carefully.',
    '3-31': 'The suffix \'-sion\' makes a /zhun/ sound (e.g. vision, confusion, division, revision). This soft, buzzing sound is different from the \'-tion\' ending. \'-sion\' is often used when the base word ends in \'d\', \'de\', or \'s\' (e.g. decide → decision, revise → revision).',
    '3-32': 'These words are complex and include unusual or mixed spelling patterns. They are commonly used words worth practising carefully.',
    '3-33': 'These words are drawn from rules taught earlier in the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '3-34': 'These words are drawn from rules taught earlier in the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '3-35': 'These words are drawn from rules taught earlier in the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '3-36': 'These words are drawn from rules taught earlier in the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '4-1': 'Homophones are words that sound the same but have different spellings and meanings (e.g. accept/except, peace/piece, plain/plane, weather/whether). Context — the meaning of the word in a sentence — tells you which spelling to use.',
    '4-2': 'The prefix \'in-\' means \'not\' and gives a word the opposite meaning (e.g. incorrect = not correct, invisible = not visible, inactive = not active). The spelling \'in-\' is kept before most letters.',
    '4-3': 'These prefixes all mean \'not\' but change form depending on the first letter of the base word. \'il-\' is used before \'l\' (e.g. illegal), \'im-\' before \'m\' or \'p\' (e.g. impossible, immature) and \'ir-\' before \'r\' (e.g. irregular, irresponsible).',
    '4-4': 'The prefix \'sub-\' means \'below\', \'under\' or \'further divided\' (e.g. submarine = under the sea, subheading = a heading beneath the main heading, subdivide = divide further). Recognising \'sub-\' helps with understanding the meaning of longer words.',
    '4-5': 'The prefix \'inter-\' means \'between\' or \'among\' (e.g. international = between nations, internet = a network between computers, intercity = between cities). Recognising \'inter-\' helps explain the meaning of many longer words.',
    '4-6': 'These words contain irregular or complex spelling patterns. They include commonly used words worth practising carefully (e.g. grammar, calendar, women, believe, straight, interest).',
    '4-7': 'The suffix \'-ation\' turns a verb into a noun and is used when the base word ends in \'-ate\' (e.g. decorate → decoration, vibrate → vibration, register → registration). The \'-ate\' is replaced by \'-ation\' to make the noun.',
    '4-8': 'The suffix \'-ation\' can also be added to verbs that do not end in \'-ate\', sometimes by dropping a final \'e\' (e.g. admire → admiration, donate → donation, explore → exploration). The ending always makes an /ay-shun/ sound.',
    '4-9': 'The suffix \'-ly\' turns an adjective into an adverb — a word that describes how something is done (e.g. sad → sadly, brave → bravely, gentle → gently). For most words, \'-ly\' is added directly to the adjective without changing it.',
    '4-10': 'Some adverbs end in \'-lly\' because the base word already ends in \'l\' (e.g. usual → usually, final → finally, beautiful → beautifully). These are formed by adding \'-ly\' to words ending in \'-al\', which results in the double \'l\' pattern.',
    '4-11': 'In words borrowed from French, \'ch\' makes a /sh/ sound rather than the usual /ch/ sound (e.g. chef, machine, brochure, chalet). These words need to be learned as a group since they do not follow the standard English \'ch\' rule.',
    '4-12': 'These words are complex and include irregular or less predictable patterns. They are commonly used words worth careful practice (e.g. favourite, complete, continue, experiment, February, knowledge).',
    '4-13': 'The suffix \'-sion\' makes a /zhun/ sound and is often used when the base word ends in \'d\', \'de\' or \'se\' (e.g. extend → extension, explode → explosion, confuse → confusion). This is different from \'-tion\', which makes a /shun/ sound.',
    '4-14': 'The suffix \'-ous\' means \'full of\' or \'having the quality of\' and turns a noun into an adjective (e.g. danger → dangerous, mountain → mountainous, marvel → marvellous). The \'-ous\' ending makes an /us/ sound.',
    '4-15': 'When \'-ous\' is added to a word ending in \'ge\', the \'e\' is kept to preserve the soft /j/ sound of the \'g\' (e.g. courage → courageous, outrage → outrageous). Without the \'e\', the \'g\' would make a hard /g/ sound.',
    '4-16': 'When a word ends in a consonant followed by \'y\', the \'y\' changes to \'i\' before most suffixes are added (e.g. merry → merriment, happy → happiness, penny → penniless). The exception is \'-ing\', where the \'y\' is kept.',
    '4-17': 'The endings \'-ious\' and \'-eous\' make an /ee-us/ sound and form adjectives (e.g. serious, obvious, curious, spontaneous, courteous). These endings are common in more formal vocabulary.',
    '4-18': 'These words are complex and contain unusual spelling patterns. They include important words used across a range of subjects (e.g. extreme, medicine, thought, business, possession).',
    '4-19': 'The digraph \'au\' makes an /or/ sound in many words (e.g. author, autumn, launch, cause, audience). This is one of the most common spellings for the /or/ sound alongside \'or\', \'aw\' and \'ore\'.',
    '4-20': 'The suffix \'-tion\' makes a /shun/ sound and turns a verb into a noun (e.g. invent → invention, select → selection, migrate → migration). This is one of the most common noun-forming suffixes in English.',
    '4-21': 'The suffix \'-sion\' makes a /shun/ sound (rather than /zhun/) when it follows certain consonants, particularly \'ss\' or \'mit\' patterns (e.g. express → expression, discuss → discussion, permit → permission). These often come from verbs where the base ends in \'ss\'.',
    '4-22': 'The suffix \'-cian\' means \'a person skilled in something\' and makes a /shun/ sound (e.g. musician, magician, electrician, mathematician). It is used when the base word ends in \'c\' or \'cs\' (e.g. music → musician, magic → magician).',
    '4-23': 'Adverbs of manner describe how an action is done and usually end in \'-ly\' (e.g. reluctantly, generously, furiously, curiously). They tell the reader more about the verb — for example, \'she spoke quietly\' tells us how she spoke.',
    '4-24': 'These words contain complex or unexpected spelling patterns. They are commonly used words worth practising carefully (e.g. surprise, separate, height, potatoes, through, caught).',
    '4-25': 'Homophones are words that sound the same but have different spellings and meanings (e.g. scene/seen, affect/effect, hear/here, heal/heel). Understanding the meaning is the key to choosing the right spelling.',
    '4-26': 'When \'c\' comes before \'i\' or \'e\', it usually makes a soft /s/ sound (e.g. circle, princess, celebrate, medicine, pencil). This is the same \'soft c\' rule seen in earlier stages but applied here to longer and more complex words.',
    '4-27': 'The root \'sol\' relates to dissolving or solutions (e.g. solve, solution, insoluble, dissolve). The root \'real\' relates to what is real or true (e.g. real, reality, realistic, realisation). Knowing the root helps to understand and spell families of related words.',
    '4-28': 'The root \'phon\' comes from Greek and means \'sound\' (e.g. telephone, microphone, phonics, homophone). The root \'sign\' relates to a mark or signal (e.g. signal, signature, design, assign). Recognising roots helps with reading and spelling longer words.',
    '4-29': '\'super-\' means \'above\' or \'greater than\' (e.g. superstar, superhuman). \'anti-\' means \'against\' (e.g. antiseptic, anticlockwise, antisocial). \'auto-\' means \'self\' or \'by itself\' (e.g. autograph, automatic). Knowing these prefixes helps with understanding and spelling longer words.',
    '4-30': 'The prefix \'bi-\' means \'two\' (e.g. bicycle = two wheels, biannual = twice a year, bilingual = speaking two languages, bicentennial = two hundred years). Recognising \'bi-\' helps you understand the meaning of a word.',
    '4-31': 'These words have complex or irregular spelling patterns. They are important everyday words worth learning carefully (e.g. guide, possess, accident, occasion, Wednesday, forward).',
    '4-32': 'When a plural noun already ends in \'s\', only an apostrophe is added after the \'s\' to show possession (e.g. girls\' = belonging to the girls, boys\' = belonging to the boys). For irregular plurals not ending in \'s\', apostrophe + \'s\' is added (e.g. children\'s, men\'s, women\'s).',
    '4-33': 'These words are drawn from rules taught throughout the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '4-34': 'These words are drawn from rules taught throughout the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '4-35': 'These words are drawn from rules taught throughout the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '4-36': 'These words are drawn from rules taught throughout the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '5-1': 'The endings \'-tious\' and \'-ious\' make an /us/ sound and form adjectives (e.g. ambition → ambitious, fiction → fictitious, repetition → repetitious). The choice of ending depends on the base word — \'-tious\' is used when the root contains a \'t\'.',
    '5-2': 'The ending \'-cious\' makes a /shus/ sound (e.g. delicious, precious, suspicious, ferocious). The \'c\' in this pattern makes a /sh/ sound because it is followed by \'i\', and the whole ending sounds /shus/.',
    '5-3': 'The ending \'-cial\' makes a /shul/ sound and usually follows a vowel (e.g. facial, official, special, artificial). The \'c\' makes a /sh/ sound because it is followed by \'i\'.',
    '5-4': 'The ending \'-tial\' makes a /shul/ sound and usually follows a consonant (e.g. essential, potential, confidential, residential). Like \'-cial\', the \'t\' makes a /sh/ sound because it is followed by \'i\'.',
    '5-5': 'Both \'-cial\' and \'-tial\' make a /shul/ sound. As a general guide, \'-cial\' follows a vowel (e.g. facial, special) and \'-tial\' follows a consonant (e.g. essential, partial, torrential). Learning what comes before the ending helps you choose the right spelling.',
    '5-6': 'These words are complex and include unusual or irregular patterns. They are important in formal and academic contexts and need careful practice (e.g. appreciate, environment, vegetable, thorough, convenient).',
    '5-7': 'The suffix \'-ant\' makes an /unt/ sound and often forms adjectives (e.g. dominant, fragrant, tolerant, elegant, brilliant). These can be difficult to spell because the ending sounds identical to \'-ent\', so individual words need to be learned.',
    '5-8': 'The suffixes \'-ance\' and \'-ancy\' form nouns related to \'-ant\' adjectives (e.g. dominant → dominancy, elegant → elegance, tolerate → tolerance). These endings make an /uns/ or /unsee/ sound and are linked to their \'-ant\' base words.',
    '5-9': 'The endings \'-ent\' and \'-ence\' work together — \'-ent\' usually forms adjectives and \'-ence\' the corresponding noun (e.g. confident → confidence, frequent → frequency, violent → violence). These sound similar to \'-ant\' and \'-ance\', so individual words must be learned.',
    '5-10': 'The suffixes \'-able\' and \'-ible\' both mean \'can be done\' or \'worthy of\' (e.g. comfortable, enjoyable, horrible, possible, incredible). \'-able\' is more common and tends to attach to recognisable English base words; \'-ible\' tends to appear with roots from Latin.',
    '5-11': '\'-ably\' and \'-ibly\' are adverbs formed by adding \'-ly\' to \'-able\' and \'-ible\' words respectively (e.g. comfortable → comfortably, horrible → horribly, sensible → sensibly). The ending sound is the same but the spelling depends on the root.',
    '5-12': 'These words are complex and commonly misspelled. They appear frequently in formal writing and are worth careful practice (e.g. accommodate, marvellous, sincerely, controversy, dictionary, opportunity).',
    '5-13': 'When a root word ends in \'ce\' or \'ge\', the final \'e\' is kept before adding \'-able\'. This preserves the soft sound of the \'c\' or \'g\' (e.g. notice → noticeable, change → changeable, manage → manageable, replace → replaceable). Without the \'e\', the \'c\' or \'g\' would make a hard sound.',
    '5-14': 'Adverbs of time tell us when, how often or in what sequence something happens (e.g. afterwards, eventually, previously, immediately, recently, whilst, yesterday). They give the reader a sense of timing and sequence.',
    '5-15': 'When \'fer\' is the stressed syllable in the base word, the \'r\' is doubled before a vowel suffix (e.g. refer → referring, prefer → preferred). When the stress moves away from \'fer\' in the new word, the \'r\' is not doubled (e.g. prefer → preference, refer → referee).',
    '5-16': 'Some words begin with a letter that is not sounded when the word is said aloud (e.g. knife — silent \'k\', write — silent \'w\', mnemonic — silent \'m\', pterodactyl — silent \'p\'). These silent letters often come from older English or other languages.',
    '5-17': 'Some words contain a letter within or at the end that is written but not pronounced (e.g. doubt — silent \'b\', island — silent \'s\', solemn — silent \'n\', thistle — silent \'t\'). These silent letters are often clues to a word\'s origins or related word family.',
    '5-18': 'These words contain unusual or complex spelling patterns and are important in formal and academic contexts. They need to be learned carefully (e.g. ancient, criticise, equipped, leisure, opportunity, sincerely).',
    '5-19': 'The familiar rule \'i before e except after c\' refers to the /ee/ sound spelled \'ei\' after \'c\'. However, when \'c\' makes a /sh/ sound — as in \'-cient\' or \'-cience\' — \'ie\' can follow \'c\' without breaking the rule (e.g. science, efficient, sufficient, species). These words need to be recognised as a distinct pattern.',
    '5-20': 'In some words, \'ei\' makes a long /ee/ sound rather than the more common /ay/ sound (e.g. caffeine, perceive, receive, ceiling, seize, protein). Many of these occur after \'c\', which supports the \'i before e except after c\' rule, but some (e.g. seize, neither) are exceptions.',
    '5-21': 'The letter string \'ough\' can make several different sounds. In these words, it makes an /or/ sound (e.g. thought, bought, fought, ought, wrought). The \'gh\' is silent and only the /or/ sound is heard.',
    '5-22': 'The letter string \'ough\' is one of the most irregular in English — it can make many different sounds (e.g. /oa/ in though, /ow/ in bough, /uf/ in rough, /of/ in cough, /oo/ in through). Each word needs to be learned individually.',
    '5-23': 'Adverbs of possibility show how likely something is (e.g. certainly, definitely, probably, possibly, rarely). Adverbs of frequency show how often something happens (e.g. often, occasionally, frequently, infrequently). Both types give more information about a verb.',
    '5-24': 'These words are complex and contain unusual spelling patterns. They are frequently used in formal and academic writing and worth careful practice (e.g. communicate, nuisance, queue, restaurant, rhythm, conscience).',
    '5-25': 'Homophones sound exactly the same but are spelled differently (e.g. advice/advise, licence/license). Near homophones sound very similar but not quite identical (e.g. practice/practise — the noun and verb forms). Understanding meaning and grammar helps you choose the right word.',
    '5-26': 'Homophones are words that sound exactly the same but have different spellings and meanings (e.g. aisle/isle, allowed/aloud, altar/alter, farther/father). Knowing the meaning and role of each word in a sentence is the key to choosing correctly.',
    '5-27': 'Homophones are words that sound exactly the same but have different spellings and meanings (e.g. bridal/bridle, heard/herd, morning/mourning, passed/past). Understanding the context and meaning of a sentence helps you choose the correct word.',
    '5-28': 'Some of these pairs are true homophones (e.g. who\'s/whose, affect/effect) and some are near homophones easily confused (e.g. desert/dessert, precede/proceed). Learning the meaning and grammatical role of each word is the key to using the right spelling.',
    '5-29': 'Some of these words look or sound very similar and are easily confused (e.g. cereal/serial, complement/compliment, stationary/stationery, principal/principle). Memory tricks can help — for example, stationEry is for Envelopes.',
    '5-30': 'These words are complex and contain unusual or irregular patterns. They are important words used across a range of contexts and worth learning carefully.',
    '5-31': 'Hyphens are used to join words together, particularly when a prefix ending in a vowel is added before a word beginning with a vowel (e.g. re-enter, co-operate, re-evaluate). Without a hyphen, the letters would run together in a confusing or ambiguous way.',
    '5-32': 'These words are complex and important in formal and academic contexts. They are frequently used but easily misspelled and are worth careful practice (e.g. amateur, ancient, changeable, referring, sincere, immediate).',
    '5-33': 'These words are drawn from rules taught throughout the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '5-34': 'These words are drawn from rules taught throughout the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '5-35': 'These words are drawn from rules taught throughout the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '5-36': 'These words are drawn from rules taught throughout the year. Revisiting them helps to consolidate spelling and build long-term memory.',
    '6-1': 'In words with Greek origins, \'y\' is used in the middle of a word to make a short /i/ sound — the same sound as \'i\' in \'it\' or \'him\' (e.g. symbol, crystal, myth, system, typical, oxygen). These words need to be learned as a group.',
    '6-2': 'In some words, \'y\' makes a long /igh/ sound, usually in the middle or at the end of the word (e.g. apply, identify, recycle, hygiene, python, supply). This is the same sound as \'high\' or \'my\'.',
    '6-3': 'These words contain unusual or complex spelling patterns. They are important in formal contexts and worth careful and repeated practice (e.g. ancient, cemetery, government, criticise, equipped, recognise).',
    '6-4': 'When \'cial\' follows a vowel, the \'c\' makes a /sh/ sound and the whole ending is pronounced /shul/ (e.g. artificial, facial, official, racial, special, superficial). Recognising this pattern helps with many formal adjectives.',
    '6-5': 'The ending \'tial\' makes a /shul/ sound after a consonant (e.g. confidential, essential, influential, potential, spatial, torrential). The \'t\' makes a /sh/ sound because it is followed by \'i\'. This pattern appears frequently in formal and academic vocabulary.',
    '6-6': 'These words are complex, commonly used in formal writing and often misspelled. They are worth careful and repeated practice (e.g. amateur, category, correspond, environment, frequently, queue, twelfth).',
    '6-7': 'These words contain unusual patterns or require careful attention to unstressed syllables. They appear across a range of academic and formal contexts and are worth learning carefully (e.g. appreciate, communicate, exaggerate, harass, marvellous, persuade, stomach, vehicle).',
    '6-8': 'In some words, \'ou\' or \'ow\' makes an /oa/ sound rather than the more common /ow/ sound (e.g. shoulder, mould, blown, soul, window, thrown). These are less common spellings for the /oa/ sound and need to be learned individually.',
    '6-9': 'When \'c\' is followed by \'e\', it makes a soft /s/ sound (e.g. celebrate, certificate, December, cemetery). This is the same soft \'c\' rule seen in earlier stages but applied here to longer and more complex words.',
    '6-10': 'These words are complex and contain unusual spelling patterns. They are important in formal and academic writing and worth careful practice (e.g. apparent, committee, guarantee, parliament, recommend, soldier, vegetable).',
    '6-11': 'The letters \'ph\' make an /f/ sound and come from Greek words (e.g. alphabet, elephant, dolphin, telephone, sphere, pheasant). Recognising this pattern helps with reading and spelling many scientific and academic words.',
    '6-12': 'These words include complex patterns and are frequently used in formal contexts. They require careful practice to avoid common misspellings (e.g. according, awkward, conscious, dictionary, familiar, neighbour, sacrifice).',
    '6-13': 'The suffix \'-ably\' forms adverbs from \'-able\' adjectives (e.g. comfortable → comfortably, noticeable → noticeably, dependable → dependably). The ending sounds /ublee/ and describes how something is done in a way that is possible or appropriate.',
    '6-14': 'The suffix \'-ible\' means \'can be done\' or \'capable of\' and tends to attach to roots from Latin (e.g. possible, responsible, reversible, visible, legible, forcible). These words often have no separate recognisable English base word, unlike \'-able\' words.',
    '6-15': 'These words are complex and include words that are commonly misspelled even in formal writing. They are worth careful and systematic practice (e.g. attached, community, desperate, excellent, hindrance, mischievous, restaurant, sufficient, yacht).',
    '6-16': 'The suffix \'-ibly\' forms adverbs from \'-ible\' adjectives (e.g. possible → possibly, horrible → horribly, responsible → responsibly, sensible → sensibly). The ending sounds the same as \'-ably\' but the spelling depends on whether the root takes \'-ible\'.',
    '6-17': 'The endings \'-ent\' and \'-ence\' work as a pair — \'-ent\' forms adjectives and \'-ence\' forms the matching noun (e.g. convenient → convenience, different → difference, excellent → excellence, silent → silence). Learning them in pairs helps with both spelling and meaning.',
    '6-18': 'These words are complex and include words important in formal, literary and academic writing. They are worth careful practice (e.g. accommodate, available, competition, determined, existence, prejudice, suggest).',
    '6-19': 'These words include some of the most commonly confused or misspelled words in formal writing. They need regular attention and practice (e.g. aggressive, bruise, convenience, embarrass, interrupt, occupy, pronunciation, thorough).',
    '6-20': 'The endings \'-er\', \'-or\' and \'-ar\' can all make the same unstressed /uh/ sound (called a schwa) at the end of a word (e.g. teacher, radiator, popular, interior, shoulder). There is no consistent rule for which ending to use — the correct spelling must be learned for each word.',
    '6-21': 'These words are complex and include words from a range of formal and academic contexts. They are worth careful and repeated practice (e.g. achieve, bargain, controversy, disastrous, foreign, interfere, nuisance, programme, secretary, temperature).',
    '6-22': 'Many words begin with \'acc-\', using a double \'c\' at the start (e.g. accommodate, accompany, accomplish, access, accumulate, accuracy). These are easily misspelled with a single \'c\', so remembering that this group shares the \'acc-\' pattern is helpful.',
    '6-23': '\'dis-\' and \'un-\' mean \'not\' or \'opposite of\' (e.g. dissatisfied, unnecessary). \'over-\' means \'too much\' or \'above\' (e.g. overreact, overrule, overseas). \'im-\' means \'not\' (e.g. impatient). In each case, the spelling of the base word stays the same when the prefix is added.',
    '6-24': 'These words are complex and include important words in a range of formal and creative contexts. They are worth careful practice (e.g. accompany, average, conscience, develop, immediately, necessary, privilege, rhythm).',
    '6-25': 'English has borrowed words from many other languages, and the spelling often reflects the original language rather than standard English patterns (e.g. ballet from French, bungalow from Hindi, blizzard from Norwegian, pyjamas from Urdu, gymkhana from Hindustani).',
    '6-26': 'These are words used to describe how language works (e.g. adverb, clause, determiner, pronoun, modal, bracket, cohesion, parenthesis). Understanding these terms helps when discussing, analysing and improving writing.',
    '6-27': 'These are further words used to talk about grammar and language structure (e.g. active, passive, antonym, synonym, hyphen, ellipsis, subject, object, colon). Learning these terms helps when analysing texts and editing writing precisely.',
    '6-28': 'The prefix \'over-\' means \'too much\', \'above\' or \'beyond\' (e.g. overreact = react too strongly, overtired = too tired, overthrow = bring down, overlooked = missed). Adding \'over-\' changes the meaning of the word but does not change the spelling of the base word.',
    '6-29': 'The suffix \'-ful\' means \'full of\' or \'having the quality of\' (e.g. faithful = full of faith, fearful = full of fear, merciful = showing mercy). Note that \'-ful\' is always spelled with one \'l\', not two.',
    '6-30': 'These are adjectives used to describe places and environments in writing (e.g. bustling, majestic, sinister, tranquil, picturesque, noiseless, unsightly). Using precise adjectives helps create a vivid picture for the reader and establishes the atmosphere of a scene.',
    '6-31': 'These are adjectives used to describe emotions precisely (e.g. apprehensive, euphoric, despondent, jittery, sanguine, incensed, terrified). Using specific emotional vocabulary creates more engaging writing than relying on general words like \'happy\' or \'sad\'.',
    '6-32': 'These are adjectives used to describe the qualities of characters in writing (e.g. amiable, courageous, obnoxious, gargantuan, valiant, exquisite, disagreeable). A wider, more precise vocabulary helps writers create vivid and well-rounded characters.',
    '6-33': 'Some words function as both a noun and a verb depending on how they are used in a sentence (e.g. \'a contest\' (noun) / \'to contest a decision\' (verb), \'the impact\' (noun) / \'to impact something\' (verb)). The word\'s role in the sentence determines its meaning.',
    '6-34': 'Some words contain vowels that are difficult to hear clearly when spoken — called schwas (e.g. the \'e\' in secretary, the first \'e\' in definitely, the \'o\' in poisonous, the \'a\' in temperature). These unstressed vowels often cause spelling errors, so it helps to learn the full written form carefully.',
    '6-35': 'These are adverbs that describe doing something with persistence and determination (e.g. persistently, relentlessly, resolutely, tenaciously, purposefully, diligently). Using precise adverbs like these creates more powerful writing than phrases like \'kept trying\' or \'didn\'t give up\'.',
    '6-36': 'These are words used in mathematics to describe operations, properties and concepts (e.g. circumference, diameter, horizontal, parallel, multiplication, calculation, division, subtraction). Spelling and understanding these terms accurately helps when reading, writing and discussing maths.',
}